### ISSUE TITLE
Package Update

### ISSUE THREAD

**Issue by Linuturk** [rax-brazil/pub-ssh-keys#4]
Why are we doing package updates here? @rackerroush

**Comment by rackerroush** [comment]
Initially I was looking to do some possible installs such as git since I was originally using git to pull down data.  It was simpler to use wget or curl since it looks like all the the images already have those two already installed.   It was also originally intended to be something that was on new systems that only we would access, but it's need has expanded beyond that.

At this point, I would probably remove the system update unless there is going to be a reason to do any installs.
